06_TP_MVC/Controllers/ProductsController.cs
using _06_TP_MVC.Models;
using _06_TP_MVC.Services;
using _06_TP_MVC.Tools;
using _06_TP_MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Utilities;

namespace _06_TP_MVC.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductsServices _services;

        private readonly IWebHostEnvironment _webHostEnvironment;


        public ProductsController(IProductsServices services, IWebHostEnvironment webHostEnvironment)
        {
            _services = services;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var products = (await _services.GetAll(new PagingViewModel<Product> { PageSize = 50})).Items;

            string uploads = Path.Combine(_webHostEnvironment.WebRootPath, "products", "mes_produits.csv");

            if (products is not null)
            {
                Serialize.ExportCSV(uploads, products);
            }

            return View(products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
            {
                return new StatusCodeResult(StatusCodes.Status400BadRequest);
            }

            var product = await _services.GetById((int)id); // (int)id <=> cast de int? vers int

            if (product is null)
            {
                //return NotFound();
                Response.StatusCode = 404;
                return View("ProductNotFound", id.Value);
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                await _services.Create(product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _services.GetById((int)id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,Price")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _services.Update(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _services.GetById((int)id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _services.Delete(id);

            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _services.GetById(id) is not null;
        }


        // -----------------------------------------------
        // ----------------- Ajax filterd ----------------
        // -----------------------------------------------

        public async Task<IActionResult> IndexFiltered()
        {
            return View((await _services.GetAll()).Items);
        }

        public async Task<IActionResult> _GetByDescription(string desc)
        {
            // return PartialView("_ProductsPage", await _dao.GetAll(desc));

            PagingViewModel<Product> vm = new()
            {
                Filter = desc
            };

            return PartialView("_ProductsPage", (await _services.GetAll(vm)).Items);
        }

        // -----------------------------------------------
        // --------- Ajax filterd Unobstrusive -----------
        // -----------------------------------------------

        public async Task<IActionResult> IndexFilteredUnobstrusive()
        {
            return View(await _services.GetAll());
        }


        public async Task<IActionResult> _IndexPartial(PagingViewModel<Product> vm)
        {
            return PartialView("_ProductsPage", (await _services.GetAll(vm)).Items);
        }

        // -----------------------------------------------
        // ------------------- PAGINATION ----------------
        // -----------------------------------------------

        public async Task<IActionResult> IndexPagined(
            [FromQuery] int p = 1,
            [FromQuery] int s = 3,
            [FromQuery] string q = ""
            )
        {
            PagingViewModel<Product> vm = new()
            {
                Filter = q,
                PageSize = s,
                CurrentPage = p
            };

            return View(await _services.GetAll(vm));
        }


        public async Task<IActionResult> IndexAjaxPagined(
           [FromQuery] int p = 1,
           [FromQuery] int s = 3,
           [FromQuery] string q = ""
           )
        {
            var model = await _services.GetAll(new PagingViewModel<Product>()
            {
                Filter = q,
                PageSize = s,
                CurrentPage = p
            });

            bool isAjax = Request.Headers["X-Requested-With"] == "XMLHttpRequest";

            if (isAjax is true)
            {
                return PartialView("_IndexPartialPagined", model);
            }

            return View(model);
        }

        // -----------------------------------------------
        // --------------------- SCROLL ------------------
        // -----------------------------------------------

        public async Task<IActionResult> IndexScroll()
        {
            return View(await _services.GetAll(new PagingViewModel<Product>() { PageSize = 14}));
        }

        public async Task<IActionResult> _IndexScrollPartial(PagingViewModel<Product> vm)
        {
            return PartialView("_IndexScrollPartial", await _services.GetAll(vm));
        }

        public async Task<IActionResult> _NextPage(PagingViewModel<Product> vm)
        {
            vm.CurrentPage++;

            return PartialView("_ProductsPage", (await _services.GetAll(vm)).Items);
        }


        // -----------------------------------------------
        // ------------ PAGINED AND SORTED ---------------
        // -----------------------------------------------

        public async Task<IActionResult> IndexPaginedAndSorted(
           [FromQuery] int p = 1,
           [FromQuery] int s = 2,
           [FromQuery] string q = "",
           [FromQuery] string sort = "description",
           [FromQuery] SortDirection direction = SortDirection.Asc)
        {
            PagingViewModel<Product> vm = new()
            {
                Filter = q,
                PageSize = s,
                CurrentPage = p,
                OrderBy = sort,
                Direction = direction
            };

            return View(await _services.GetAll(vm));
        }
    }
}

06_TP_MVC/Controllers/UsersController.cs
using _06_TP_MVC.Models;
using _06_TP_MVC.Services;
using _06_TP_MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _06_TP_MVC.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUsersServices _services;

        public UsersController(IUsersServices services)
        {
            _services = services;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View((await _services.GetAll()).Items);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _services.GetById((int)id); // (int)id <=> cast de int? vers int
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Email,Password,IsAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                await _services.Create(user);
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _services.GetById((int)id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Email,Password,IsAdmin")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _services.Update(user);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _services.GetById((int)id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _services.Delete(id);

            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _services.GetById(id) is not null;
        }

        // -----------------------------------------------
        // ------------------- PAGINATION ----------------
        // -----------------------------------------------

        public async Task<IActionResult> IndexPagined(
            [FromQuery] int p = 1,
            [FromQuery] int s = 3,
            [FromQuery] string q = ""
            )
        {
            PagingViewModel<User> vm = new()
            {
                Filter = q,
                PageSize = s,
                CurrentPage = p
            };

            return View(await _services.GetAll(vm));
        }
    }
}

06_TP_MVC/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<h1 class="text-danger">@ViewBag.ErrorMessage</h1>
<h1 class="text-danger">@ViewBag.Path</h1>
<h1 class="text-danger">@ViewBag.QS</h1>

<a asp-controller="Home" asp-action="Index">Home sweet home</a>

06_TP_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _06_TP_MVC</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/BootSwachtSolarTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <!-- ------------------------ CSS TOASTR --------------------- -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">_06_TP_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Products</a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Products" asp-action="Index">Default</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Products" asp-action="IndexFiltered">Ajax filterd</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Products" asp-action="IndexFilteredUnobstrusive">Ajax filterd Unobstrusive</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Products" asp-action="IndexPagined">Pagined</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Products" asp-action="IndexAjaxPagined">Ajax Pagined</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Products" asp-action="IndexScroll">Scroll</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Products" asp-action="IndexPaginedAndSorted">Pagined And Sorted</a>
                                </li>
                            </ul>
                        </li>


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Users</a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Users" asp-action="Index">Default</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Users" asp-action="IndexPagined">Pagined</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"/>
            <alert-success render-mode="Bootstrap5" show-icons=true icons-source="Bootstrap5"></alert-success>
            <alert-danger render-mode="Bootstrap5" show-icons=true icons-source="Bootstrap5"></alert-danger>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _06_TP_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <!-- ------------------------ CDN AJAX UNOBSTRUSIVE --------------------- -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

06_TP_MVC/Views/Shared/_NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<h1 class="text-danger">@ViewBag.ErrorMessage</h1>
<h1 class="text-danger">@ViewBag.Path</h1>
<h1 class="text-danger">@ViewBag.QS</h1>
<a asp-action="Index" asp-controller="Home">Home Sweet Home</a>

06_TP_MVC/Views/Shared/_Notification.cshtml
@if (TempData["success"] is not null)
{
    <!-- https://github.com/CodeSeven/toastr -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}